#!/bin/bash
mgr_dir=`cd $(dirname $0);pwd`

source $mgr_dir/lib.sh

function Usage() {
    echo "$0 { list | deploy-c <name> | restore-c <name> | fetch <storage> <name>/all }"
    exit 1
}


case "$1" in 
    deploy-c)
        Parameter_judge 2 $#
        Deploy_Client $2
        ;;

    restore-c)
        Parameter_judge 2 $#
        Restore_Client $2
        ;;

    list)
        Parameter_judge 1 $#
        List
        ;;

    fetch)
        Parameter_judge 3 $#
        Fetch $2 $3
        ;;

    *)
        Usage
        ;;
esac